### ISSUE TITLE
Anonymization scanner tried to download zh_core_web_sm model even if language specified is only english

### ISSUE THREAD

**Issue by rajatm91** [protectai/llm-guard#227]
**Describe the bug**
Anonymization scanner tried to download zh_core_web_sm model even if language specified is only english

Config for the scanner : 
- type: Anonymize
    params:
      use_faker: false
      threshold: 0.75
      model_path: "./distilbert_finetuned_ai4privacy_v2"
      language: "en"

and I have installed en_core_web_sm model in my environment

**Expected behavior**
it shouldn't download new models 

**Additional context**
I think the issue is at this [line](https://github.com/protectai/llm-guard/blob/main/llm_guard/input_scanners/anonymize.py#L125) where its not using the `language` parameter pass to the class but using a global variable `ALL_SUPPORTED_LANGUAGES` which includes `en` and `zh`.

**Comment by asofter** [comment]
Hey @rajatm91 , thanks for the question. Yes, this is how it would work since the supported languages need to be provided upfront (example from the presidio itself: https://github.com/microsoft/presidio/blob/main/docs/samples/python/ner_model_configuration.ipynb).

You can override the `ALL_SUPPORTED_LANGUAGES` to be only `['en`]` which will solve this issue.

**Comment by rajatm91** [comment]
Hi @asofter 
Thanks for the reply. 
Could you help how can I override the `ALL_SUPPORTED_LANGUAGES` variable as part of the llm-guard config. My current config looks like this: 
```
input_scanners:
  - type: Anonymize
    params:
      use_faker: false
      threshold: 0.75
      model_path: ${MODEL_DIR}/deberta-v3-base_finetuned_ai4privacy_v2
      language: en
```
